Bump Kani version to 0.46.0
model-checking/kani pull request #3013
Opened 2024-02-08 23:11 UTC by feliperodri

## What's Changed
* `modifies` Clauses for Function Contracts by @JustusAdam in https://github.com/model-checking/kani/pull/2800
* Enable powf*, exp*, log* intrinsics by @tautschnig in https://github.com/model-checking/kani/pull/2996
* Upgrade Rust toolchain to nightly-2024-01-23 by @celinval in https://github.com/model-checking/kani/pull/2983
* Upgrade Rust toolchain to nightly-2024-01-24 by @feliperodri in https://github.com/model-checking/kani/pull/3008

**Full Changelog**: https://github.com/model-checking/kani/compare/kani-0.45.0...kani-0.46.0

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

2024-02-08 23:16 UTC, jaisnan approved these changes
Thanks!

2024-02-08 23:43 UTC, celinval requested changes
Can you please include https://github.com/model-checking/kani/pull/2994 to the release notes. We might want to edit the message to include the issues that were fixed. Thanks

2024-02-09 00:13 UTC, celinval commented on CHANGELOG.md
> +  * https://github.com/model-checking/kani/issues/1350
```suggestion
  * https://github.com/model-checking/kani/issues/2260
  * https://github.com/model-checking/kani/issues/2312
```

2024-02-09 00:17 UTC, celinval commented on CHANGELOG.md
> +* Upgrade Rust toolchain to nightly-2024-01-24 by @feliperodri in https://github.com/model-checking/kani/pull/3008
We usually merge them too:
```suggestion
* Upgrade Rust toolchain to nightly-2024-01-24 by @celinval @feliperodri @qinheping
```

2024-02-09 00:17 UTC, celinval approved these changes

2024-02-09 00:49 UTC, merged